apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort  # Exposes the service on each Node’s IP at a static port
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30000