apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment-redis
  labels:
    app: node-app
spec:
  replicas: 3  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: hello-world-be:kubernetes-0.0.5
        env:
          - name: REDIS_HOST
            value: "redis-0.redis-service.default.svc.cluster.local"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP                         
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
