apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: hello-world-node:kub
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
