version: '3.8'
services:
  app:
    build: .
    image: hello-world-be:docker-compose-v3
    ports:
      - "3001:3000"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: ["npm", "run", "start:dev"]  
    depends_on:
      - redis-service
  redis-service:
    image: "redis:alpine"
